// Programador          Ant0ni0 M@ns0 - Ant0ni0 M@ns0

    inicio 
        ler real r1 "Real 1 \t: "
        ler real r2 "Real 2 \t: "
        escrever "\nDescending order\n"
        se r1 > r2 então
            escrever r1 + "\t" + r2
        senão
            escrever r2 + "\t" + r1
        fim
    fim 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	domingo, 2022 set 18 23:28
