// Programador          Ant0ni0 M@ns0 - Ant0ni0 M@ns0

    inicio 
        ler inteiro num "Number \t: "
        se num > 0 então
            escrever "Positive"
        senão
            se num == 0 então
                escrever "Null"
            senão
                escrever "Negative"
            fim
        fim
    fim 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	domingo, 2022 set 18 23:27
