// Programmer           Ant0ni0 M@ns0 - Ant0ni0 M@ns0

    begin 
        real r1 = 0.1
        real r2 = 0.2
        real r3 = 0.1 + 0.2
        write "0.1 + 0.2 = " + r3
        real r4 = 0.3 - 0.2
        write "\n0.3 - 0.2 = " + r4
        real r5 = 0.01234567890123456789
        write "\n0.01234567890123456789 = " + r5
    end 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	Mon, 2022 Sep 26 15:31
