// Programador          Ant0ni0 M@ns0 - Ant0ni0 M@ns0

    inicio 
        inteiro i
        enquanto verdadeiro faz
            escrever "Positive number : "
            ler i
            se i > 0 então
                quebrar
            fim
            escrever "Error in reading\n\n"
        fim
        escrever "Entered value = " + i
    fim 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	quarta, 2022 out 12 19:32
