// Programador           -

    inicio 
        ler inteiro altura "Altura : "
        iterar inteiro i de 1 até altura + 1  passo 1
            linha(i)
        fim
    fim 

    funcao vazio linha(inteiro n)
        iterar inteiro i de 0 até n  passo 1
            escrever "*"
        fim
        escrever "\n"
    fim 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	quarta, 2022 out 12 20:09
