// Programmer           Ant0ni0 M@ns0 - Ant0ni0 M@ns0

    begin 
        read integer num "Número \t: "
        if num == 0 then
            write "Nulo"
        else
            if num > 0 then
                write "Positivo"
            else
                write "Negativo"
            end
        end
    end 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	Mon, 2022 Sep 26 15:31
