// Programmer           Ant0ni0 M@ns0 - Ant0ni0 M@ns0

    begin 
        write "Somatório Pares [0,10]\n"
        integer soma
        for integer i from 1 to 6  step 1
            integer f = 2 * i
            write soma + " + " + f
            soma += f
            write " = " + soma + "\n"
        end
        write "\nSoma = " + soma
    end 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	Mon, 2022 Sep 26 16:13
