// Programmer           Ant0ni0 M@ns0 - Ant0ni0 M@ns0

    begin 
        write "Formula Summation\n"
        integer sum
        for integer i from 1 to 6  step 1
            integer f = 2 * i - 1
            write sum + " + " + f
            sum += f
            write " \t= " + sum + "\n"
        end
        write "\nSum= " + sum
    end 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	Fri, 2022 Sep 30 22:36
