// Programmer           Ant0ni0 M@ns0 - Ant0ni0 M@ns0

    begin 
        write "Produtório\n"
        integer produto = 1
        for integer i from 1 to 5  step 1
            write produto + " x " + i
            produto *= i
            write " = " + produto + "\n"
        end
        write "\nTotal = " + produto
    end 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	Mon, 2022 Sep 26 16:13
