// Programmer           Ant0ni0 M@ns0 - Ant0ni0 M@ns0

    begin 
        read integer inf "Inferior limit : "
        if inf % 2 == 0 then
            inf++
        end
        read integer sup "Upper limit : "
        while inf <= sup do
            write inf + " "
            inf += 2
        end
    end 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	Sat, 2022 Oct 01 00:11
