// Programmer           Ant0ni0 M@ns0 - Ant0ni0 M@ns0

    begin 
        write "Summation\n"
        integer sum
        for integer i from 1 to 6  step 1
            write sum + " + " + i
            sum++
            write " \t = " + sum + "\n"
        end
        write "\nTotal = " + sum
    end 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	Fri, 2022 Sep 30 22:36
