// Programmer           Ant0ni0 M@ns0 - Ant0ni0 M@ns0

    begin 
        read integer inf "Limite inferior : "
        if inf % 2 == 0 then
            inf++
        end
        read integer sup "Limite superior : "
        while inf <= sup do
            write inf + " "
            inf += 2
        end
    end 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	Thu, 2022 Sep 29 12:25
