// Programmer           Ant0ni0 M@ns0 - Ant0ni0 M@ns0

    begin 
        write "Productory\n"
        integer product = 1
        for integer i from 1 to 5  step 1
            write product + " x " + i
            product *= i
            write " = " + product + "\n"
        end
        write "\nTotal = " + product
    end 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	Fri, 2022 Sep 30 22:36
