// Programmer           Ant0ni0 M@ns0 - Ant0ni0 M@ns0

    begin 
        read integer n "Number of terms : "
        integer product = 1
        for integer i from 1 to n + 1  step 1
            integer f = 2 * i - 1
            product *= f
        end
        write "Result = " + product
    end 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	Fri, 2022 Sep 30 22:37
