// Programmer           Ant0ni0 M@ns0 - Ant0ni0 M@ns0

    begin 
        write "Somatório passo 2\n"
        integer soma
        for integer i from 1 to 10  step 2
            write soma + " + " + i
            soma += i
            write " \t= " + soma + "\n"
        end
        write "\nSoma = " + soma
    end 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	Mon, 2022 Sep 26 16:13
