// Programmer           Ant0ni0 M@ns0 - Ant0ni0 M@ns0

    begin 
        integer minimum = 999
        for integer i from 1 to 6  step 1
            read integer grade i + "º grade : "
            if grade < minimum then
                minimum = grade
            end
        end
        write "Nota mínima = " + minimum
    end 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	Sat, 2022 Sep 24 22:05
