// Programmer           Ant0ni0 M@ns0 - Ant0ni0 M@ns0

    begin 
        write "\n! " + true + " \t= " + !true
        write "\n! " + false + " \t= " + !false
        boolean var = 1
        if var then
            write "\nMuito Bem !"
        else
            write "\nErrado :-("
        end
    end 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	Mon, 2022 Sep 26 15:32
