// Programmer           Ant0ni0 M@ns0 - Ant0ni0 M@ns0

    begin 
        for integer n from 1 to 11  step 1
            write "\nTabuada do " + n + "\n"
            for integer i from 1 to 11  step 1
                write n + " x " + i + " = " + i * n + "\n"
            end
        end
    end 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	Fri, 2022 Sep 30 21:54
