// Programmer           Ant0ni0 M@ns0 - Ant0ni0 M@ns0

    begin 
        write "Summation step 2\n"
        integer sum
        for integer i from 1 to 10  step 2
            write sum + " + " + i
            sum += i
            write " \t= " + sum + "\n"
        end
        write "\nSum = " + sum
    end 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	Fri, 2022 Sep 30 22:36
