// Programador           -

    inicio 
        linha()
        escrever "Numeros entre 1 e 5\n"
        linha()
        iterar inteiro i de 1 até 6  passo 1
            escrever i + "\n"
        fim
        linha()
    fim 

    funcao vazio linha()
        iterar inteiro i de 0 até 20  passo 1
            escrever "*"
        fim
        escrever "\n"
    fim 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	quarta, 2022 out 12 20:09
