// Programador          Ant0ni0 M@ns0 - Ant0ni0 M@ns0

    inicio 
        line()
        escrever "Numbers between 1 and 5\n"
        line()
        iterar inteiro i de 1 até 6  passo 1
            escrever i + "\n"
        fim
        line()
    fim 

    funcao vazio line()
        iterar inteiro i de 0 até 20  passo 1
            escrever "*"
        fim
        escrever "\n"
    fim 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	quarta, 2022 out 12 20:22
