// Programador          Ant0ni0 M@ns0 - Ant0ni0 M@ns0

    inicio 
        line(3)
        line(5)
        line(7)
        line(5)
        line(3)
    fim 

    funcao vazio line(inteiro n)
        iterar inteiro i de 0 até n  passo 1
            escrever "*"
        fim
        escrever "\n"
    fim 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	quarta, 2022 out 12 20:22
