// Programador          Ant0ni0 M@ns0 - Ant0ni0 M@ns0

    inicio 
        escrever "\n! " + verdadeiro + " \t= " + !verdadeiro
        escrever "\n! " + falso + " \t= " + !falso
        logico var = 1
        se var então
            escrever "\nVery Good !"
        senão
            escrever "\nWrong :-("
        fim
    fim 


//pseudocode  - Automatic translated by Algorithmi 22.05
//(c) Ant0nio M@nso 	domingo, 2022 set 18 23:28
